export type SelectorStrategies = {
  dataTestId?: string;
  name?: string;
  placeholder?: string;
  ariaLabel?: string;
  id?: string;
  stableClasses?: string;
  nthOfType?: string;
};

/**
 * Returns true if a CSS selector matches exactly one element in the document.
 */
function isUnique(selector: string): boolean {
  try {
    return document.querySelectorAll(selector).length === 1;
  } catch {
    return false;
  }
}

/**
 * Returns true if a CSS class name looks auto-generated (CSS modules hash,
 * Tailwind JIT bracket syntax, etc.) and should not be used for stable selectors.
 */
function isGeneratedClass(cls: string): boolean {
  if (cls.startsWith("_")) return true;
  // CSS module hash suffix: 5+ alphanumeric chars after a separator
  if (/[_-][a-z0-9]{5,}$/i.test(cls)) return true;
  // Tailwind arbitrary value syntax
  if (cls.startsWith("[") || cls.includes(":[")) return true;
  return false;
}

/**
 * Returns true if an id looks generated by the runtime rather than authored
 * in app code. These ids are unique but often not stable across rerenders.
 */
function isGeneratedId(id: string): boolean {
  return id.includes(":");
}

function isVisibleElement(el: Element): boolean {
  if (!(el instanceof HTMLElement)) return true;
  const rect = el.getBoundingClientRect();
  if (rect.width === 0 && rect.height === 0) return false;

  const styles = window.getComputedStyle(el);
  return styles.display !== "none" && styles.visibility !== "hidden";
}

/**
 * Builds the nth-of-type DOM path (the legacy approach).
 */
function buildNthOfTypePath(el: Element): string {
  const parts: string[] = [];
  let current: Element | null = el;

  while (current && current !== document.documentElement) {
    let selector = current.tagName.toLowerCase();

    if (current.id && !isGeneratedId(current.id)) {
      parts.unshift(`#${CSS.escape(current.id)}`);
      break;
    }

    const parent: Element | null = current.parentElement;
    if (parent) {
      const tag = current.tagName;
      const siblings = Array.from(parent.children).filter(
        (child) => child.tagName === tag,
      );
      if (siblings.length > 1) {
        const index = siblings.indexOf(current) + 1;
        selector += `:nth-of-type(${index})`;
      }
    }

    parts.unshift(selector);
    current = parent;
  }

  return parts.join(" > ");
}

/**
 * Generates multiple selector strategies for an element, returning the most
 * stable unique selector as `best` and all strategies in `strategies`.
 *
 * Priority: data-testid > stable id > name > placeholder > aria-label
 * > stable CSS classes > nth-of-type.
 */
export function generateSelectors(el: Element): {
  best: string;
  strategies: SelectorStrategies;
} {
  const strategies: SelectorStrategies = {};

  // 1. data-testid
  const testId = el.getAttribute("data-testid");
  if (testId) {
    const selector = `[data-testid="${CSS.escape(testId)}"]`;
    if (isUnique(selector)) {
      strategies.dataTestId = selector;
    }
  }

  // 2. id
  if (el.id && !isGeneratedId(el.id)) {
    const selector = `#${CSS.escape(el.id)}`;
    if (isUnique(selector)) {
      strategies.id = selector;
    }
  }

  // 3. name
  const name = el.getAttribute("name");
  if (name && /^(input|textarea|select)$/i.test(el.tagName)) {
    const tag = el.tagName.toLowerCase();
    const type = el.getAttribute("type");
    const selector = `${tag}[name="${CSS.escape(name)}"]${type ? `[type="${CSS.escape(type)}"]` : ""}`;
    if (isUnique(selector)) {
      strategies.name = selector;
    }
  }

  // 4. placeholder
  const placeholder = el.getAttribute("placeholder");
  if (placeholder && /^(input|textarea)$/i.test(el.tagName)) {
    const tag = el.tagName.toLowerCase();
    const selector = `${tag}[placeholder="${CSS.escape(placeholder)}"]`;
    if (isUnique(selector)) {
      strategies.placeholder = selector;
    }
  }

  // 5. aria-label
  const ariaLabel = el.getAttribute("aria-label");
  if (ariaLabel) {
    const tag = el.tagName.toLowerCase();
    const selector = `${tag}[aria-label="${CSS.escape(ariaLabel)}"]`;
    if (isUnique(selector)) {
      strategies.ariaLabel = selector;
    }
  }

  // 6. Stable CSS classes
  const stableClasses = Array.from(el.classList).filter(
    (cls) => !isGeneratedClass(cls),
  );
  if (stableClasses.length > 0) {
    const tag = el.tagName.toLowerCase();
    const classSelector = stableClasses
      .map((c) => `.${CSS.escape(c)}`)
      .join("");
    const selector = `${tag}${classSelector}`;
    if (isUnique(selector)) {
      strategies.stableClasses = selector;
    }
  }

  // 7. nth-of-type path (always generated as fallback)
  strategies.nthOfType = buildNthOfTypePath(el);

  // Pick the best (first available in priority order)
  const best =
    strategies.dataTestId ??
    strategies.id ??
    strategies.name ??
    strategies.placeholder ??
    strategies.ariaLabel ??
    strategies.stableClasses ??
    strategies.nthOfType;

  return { best, strategies };
}

/**
 * Generates a best-effort unique CSS selector for a DOM element.
 * Backward-compatible wrapper around generateSelectors().
 */
export function generateSelector(el: Element): string {
  return generateSelectors(el).best;
}

/**
 * Tries to find an element using the primary selector first, then falls back
 * to each strategy in priority order. Returns null if nothing matches.
 */
export function resolveElement(
  primarySelector: string | null,
  strategies?: SelectorStrategies,
): Element | null {
  let hiddenFallback: Element | null = null;

  function resolveSelector(selector: string): Element | null {
    try {
      const matches = Array.from(document.querySelectorAll(selector));
      if (matches.length === 0) return null;

      const visibleMatch = matches.find(isVisibleElement) ?? null;
      if (visibleMatch) return visibleMatch;

      hiddenFallback ??= matches[0] ?? null;
      return null;
    } catch {
      return null;
    }
  }

  // Try primary selector first
  if (primarySelector) {
    const el = resolveSelector(primarySelector);
    if (el) return el;
  }

  if (!strategies) return hiddenFallback;

  // Try each strategy in priority order
  const ordered = [
    strategies.dataTestId,
    strategies.id,
    strategies.name,
    strategies.placeholder,
    strategies.ariaLabel,
    strategies.stableClasses,
    strategies.nthOfType,
  ];

  for (const selector of ordered) {
    if (!selector || selector === primarySelector) continue;
    const el = resolveSelector(selector);
    if (el) return el;
  }

  return hiddenFallback;
}
