name: Container image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"
      - "ongrow-*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sign in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push application image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: runner
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ongrowww/faster-fixes:${{ github.sha }}
            ghcr.io/ongrowww/faster-fixes:edge
          cache-from: type=gha,scope=runner
          cache-to: type=gha,mode=max,scope=runner

      - name: Build and push migration image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: migrator
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ongrowww/faster-fixes:${{ github.sha }}-migrator
            ghcr.io/ongrowww/faster-fixes:edge-migrator
          cache-from: type=gha,scope=migrator
          cache-to: type=gha,mode=max,scope=migrator
